replicaCount: 1

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Configuration du service
service:
  type: ClusterIP
  ports:
    client: 2181

# Désactiver l'authentification pour simplifier
auth:
  enabled: false

fullnameOverride: "zookeeper"